// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package internal

import (
	"time"

	"github.com/google/uuid"
)

type Review struct {
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
	ID         uuid.UUID `json:"id"`
	UserId     uuid.UUID `json:"userId"`
	HospitalId uuid.UUID `json:"hospitalId"`
	Content    string    `json:"content"`
	Rating     int32     `json:"rating"`
}
