// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"angmorning.com/internal/libs/db"
	"angmorning.com/internal/libs/oauth"
	"angmorning.com/internal/server"
	"angmorning.com/internal/services/auth/application"
	infrastructure2 "angmorning.com/internal/services/auth/infrastructure"
	application3 "angmorning.com/internal/services/hospitals/application"
	infrastructure3 "angmorning.com/internal/services/hospitals/infrastructure"
	presentation2 "angmorning.com/internal/services/hospitals/presentation"
	application2 "angmorning.com/internal/services/users/application"
	"angmorning.com/internal/services/users/infrastructure"
	"angmorning.com/internal/services/users/presentation"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	healthCheckHandler := server.NewHandler()
	sqlDB := db.InitDb()
	userRepository := infrastructure.New(sqlDB)
	oauthClientFactory := oauth.NewFactory()
	authRepository := infrastructure2.New(sqlDB)
	authService := application.New(authRepository)
	userService := application2.New(userRepository, oauthClientFactory, authService)
	userHandler := presentation.New(userService)
	hospitalRepository := infrastructure3.New(sqlDB)
	hospitalService := application3.New(hospitalRepository)
	hospitalHandler := presentation2.New(hospitalService)
	serverServer := server.NewServer(healthCheckHandler, userHandler, hospitalHandler)
	return serverServer, nil
}
