// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package internal

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	CreatedAt  time.Time      `json:"createdAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
	ID         int32          `json:"id"`
	UserId     uuid.UUID      `json:"userId"`
	Value      string         `json:"value"`
	ClientInfo sql.NullString `json:"clientInfo"`
}
