// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package internal

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Hospital struct {
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	DeletedAt   sql.NullTime `json:"deletedAt"`
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	Phone       string       `json:"phone"`
	City        string       `json:"city"`
	RoadAddress string       `json:"roadAddress"`
	Latitude    float64      `json:"latitude"`
	Longitude   float64      `json:"longitude"`
	ZipCode     string       `json:"zipCode"`
}
