// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package internal

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
	DeletedAt sql.NullTime `json:"deletedAt"`
	ID        uuid.UUID    `json:"id"`
	Email     string       `json:"email"`
	Nickname  string       `json:"nickname"`
	Providers []string     `json:"providers"`
}
