// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"angmorning.com/internal/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	healthCheckHandler := server.NewHandler()
	serverServer := server.NewServer(healthCheckHandler)
	return serverServer, nil
}
